### PR TITLE
Revise Editor

### PR DESCRIPTION
**Pull request by schubmat**
In order to implement a new editor (cf. #13) work has been contributed on 

`/schubmat/Custom-MADE/tree/feature-integrate-visual-editing`

However, it has not been completed yet. Currently compile errors need to be fixed which occurred based on a recent update of `sprotty` to `0.10.0.`

### CODE REVIEW

**Comment by schubmat** [comment]
@rrcomtech 

Thanks! I'm going to have a closer look at that later. 

@rrcomtech 
Integrating workspaces is a mess!

**Comment by schubmat** [comment]
@rrcomtech It boils down to the fact that it cannot be implemented platform-independently for the time being. The preferences extension doesn't really help, as it only works if you use both workspace and user config together.

**Comment by schubmat** [comment]
@rrcomtech For now, workspace configs are created in the general files folder called "files" -> ".theia/settings"

The thing that remains to be done is setting the workspace each and every time the editor opens up. :wink:

**Comment by schubmat** [comment]
@rrcomtech Workspace issue is comprehensively treated.

**Comment by schubmat** [comment]
@rrcomtech Please check out [corresponding branch](/schubmat/Custom-MADE/tree/feature-integrate-visual-editing/) and try! I had to update the package-lock. In the same breath I updated `tsc` to `3.9`. I hope this won't bring any trouble in the near future. 

I'll see whether update further @types packages is advisabe

**Comment by judgeNotFound** [comment]
It worked very well for me. Very good job! 😄

**Pull request merged**
